/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };